name: Generate Snake

# اجازه‌ی نوشتن به مخزن (همان شاخه‌ی اصلی)
permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"   # هر شب اجرا شود
  workflow_dispatch:       # امکان اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: eh3ano-0
          outputs: |
            snake/github-snake.svg
            snake/github-snake-dark.svg?palette=github-dark

      - name: Commit & Push snake SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snake/
          git diff --staged --quiet || git commit -m "🐍 Update contribution snake [skip ci]"
          git push
